### ISSUE TITLE
Strings for server connections limited to 64 characters

### ISSUE THREAD

**Issue by vsaulys** [KxSystems/kx-vscode#257]
The plugin limits the character strings to 64 characters in length, this causes issues when trying to connect to a kdb instance managed by Amazon FinSpace with Managed kdb Insights. The strings for serverName is over 64 characters, and the password is a very long signed URL

**Comment by nfarrell-kx** [comment]
Thanks for the feedback, we have raised a ticket internally to implement this

**Comment by ecmel** [comment]
@vsaulys  Raised the limit to 1024 characters. Will this be enough?

**Comment by vsaulys** [comment]
Will need 2048.

The signed connection string can be up to 2048 as per docs:

https://docs.aws.amazon.com/finspace/latest/management-api/API_GetKxConnectionString.html￼ 

Vincent Saulys
***@***.***

**Comment by ecmel** [comment]
Increased to 2048

**Comment by ecmel** [comment]
This will be in release 1.4 hopefully this week.

**Comment by ecmel** [comment]
@vsaulys  This is available in version 1.4 from marketplace.

**Comment by vsaulys** [comment]
Excellent!

Thanks for the update

Vincent Saulys
***@***.***

**Comment by ecmel** [comment]
Hello, we have implemented [custom authentication](https://github.com/KxSystems/kx-vscode-auth) feature so you can now automate your login flow for your use case.

Checkout [Portier example](https://github.com/KxSystems/kx-vscode-auth/tree/portier) for token based use case.
