### ISSUE TITLE
Display of keyed tables broken

### ISSUE THREAD

**Issue by ConorForgie** [KxSystems/kx-vscode#382]
It looks like the extension cannot display keyed tables:

```([sym: `a`b`c] val:1 2 3)```

Output tab:

sym| val
---| ---
a  | 1  
b  | 2  
c  | 3  

KDB Results tab:

0|1|2
---|---|---
[object Object]|[object Object]|[object Object]
[object Object]|[object Object]|[object Object]

**Comment by Philip-Carneiro-KX** [comment]
Fixed, it will be released at 1.9 version
